name: CI

on:
  push: master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm test:ci
      - uses: test-summary/action@v2
        with:
          paths: "junit.xml"
        if: always()
